version: '2'
services:
    blog-app:
        image: blog
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://blog-mssql:1433;database=blog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blog-mssql:
        extends:
            file: mssql.yml
            service: blog-mssql
